### ISSUE TITLE
Don't get pornhub urls

### ISSUE THREAD

**Issue by thisistorsten** [Joel2B/XVideos-PornHub-RedTube-API#2]
Using this release I am not able to get pornhub video urls. The quality json is empty.

**Comment by Joel2B** [comment]
using the main script will not work for pornhub, you need to use the [api-for-own-servers](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/tree/main/api-for-own-servers)  script for it to work,
you can place it on the same server, this script uses HTTP Request2, because another method, such as CURL, will not work

if it still doesn't work let me know

**Comment by Superion03** [comment]
Can you tell me how to get the api-for-own-servers working? Ive got the main script working, but dont know how the api-for-own-servers works.. Do i need it to call it like : https://localhosti/api-for-own-servers/?url=https://www.xvideos.com/video59934029/

**Comment by Joel2B** [comment]
yes, what [api-for-own-servers](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/tree/main/api-for-own-servers) does is to act as a proxy to make requests from it and not the main script, so you avoid burning the ip of the main server (the main script)

to use it, you must place it in the root or in any part of your server, then add it to the list of servers in [sources.json](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/blob/main/src/servers/sources.json)
following the format shown there

I will take as an example the website https://appsdev.cyou/xv-ph-rt/

the main script is at https://appsdev.cyou/xv-ph-rt/ and the [api-for-own-servers](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/tree/main/api-for-own-servers) script is in https://tmp01.appsdev.cyou/

so in [sources.json](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/blob/main/src/servers/sources.json#L37) it would look like this

```json
{
    "id": "xvideos",
    "url": "https://tmp01.appsdev.cyou/?url={url}",
    "category": ["primary"],
    "media": {
        "hls": {
            "all": "VideoHLS\\('(.*?)'\\)"
        },
        "mp4": {
            "high": "High\\('(.*?)'\\)",
            "low": "Low\\('(.*?)'\\)"
        }
    },
    "data": {
        "thumb": "ThumbUrl169\\('(.*?)'\\)",
        "duration": "duration\" content=\"(.*?)\""
    }
},
```

if the script is not in the root, indicate its location
Ex. `https://tmp01.appsdev.cyou/api-for-own-servers/?url={url}`

since we use our own server, you can set as many options as you want to get

and to test that you get content use:
https://tmp01.appsdev.cyou/?url=https://www.xvideos.com/video59934029/_&cookie_id=xvideos
changing the domain to yours

if you want to use pornhub you must use [api-for-own-servers](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/tree/main/api-for-own-servers) either on the same server or on another one

if you have more questions let me know

**Comment by Joel2B** [comment]
> > using the main script will not work for pornhub, you need to use the [api-for-own-servers](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/tree/main/api-for-own-servers) script for it to work, you can place it on the same server, this script uses HTTP Request2, because another method, such as CURL, will not work
> > if it still doesn't work let me know
> 
> Can you tell me how to get the api-for-own-servers working? Ive got the main script working, but dont know how the api-for-own-servers works.. Do i need it to call it like : https://localhosti/api-for-own-servers/?url=https://www.xvideos.com/video59934029/

yes, what [api-for-own-servers](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/tree/main/api-for-own-servers) does is to act as a proxy to make requests from it and not the main script, so you avoid burning the ip of the main server (the main script)

to use it, you must place it in the root or in any part of your server, then add it to the list of servers in [sources.json](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/blob/main/src/servers/sources.json)
following the format shown there

I will take as an example the website https://appsdev.cyou/xv-ph-rt/

the main script is at https://appsdev.cyou/xv-ph-rt/ and the [api-for-own-servers](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/tree/main/api-for-own-servers) script is in https://tmp01.appsdev.cyou/

so in [sources.json](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/blob/main/src/servers/sources.json#L37) it would look like this

```json
{
    "id": "xvideos",
    "url": "https://tmp01.appsdev.cyou/?url={url}",
    "category": ["primary"],
    "media": {
        "hls": {
            "all": "VideoHLS\\('(.*?)'\\)"
        },
        "mp4": {
            "high": "High\\('(.*?)'\\)",
            "low": "Low\\('(.*?)'\\)"
        }
    },
    "data": {
        "thumb": "ThumbUrl169\\('(.*?)'\\)",
        "duration": "duration\" content=\"(.*?)\""
    }
},
```

if the script is not in the root, indicate its location
Ex. `https://tmp01.appsdev.cyou/api-for-own-servers/?url={url}`

since we use our own server, you can set as many options as you want to get

and to test that you get content use:
https://tmp01.appsdev.cyou/?url=https://www.xvideos.com/video59934029/_&cookie_id=xvideos
changing the domain to yours

if you want to use pornhub you must use [api-for-own-servers](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/tree/main/api-for-own-servers) either on the same server or on another one

if you have more questions let me know

**Comment by Superion03** [comment]
> ?url=https://www.xvideos.com/video59934029/_&cookie_id=xvideos

Thanks for your detailed answer, its now clear.. But when I want to try fetch content from Pornhub or xvideos with the link you gave me ```https://{domain}.com/test/video/api-for-own-servers/?url=https://www.pornhub.com/view_video.php?viewkey=ph6116a13a48187/_&cookie_id=pornhub```  I get a 500 error response code. What am I doing wrong, ive checked if the http2 request is enabled on my server, and it is... You got any idea what I am doing wrong?

**Comment by Superion03** [comment]
> > > using the main script will not work for pornhub, you need to use the [api-for-own-servers](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/tree/main/api-for-own-servers) script for it to work, you can place it on the same server, this script uses HTTP Request2, because another method, such as CURL, will not work
> > > if it still doesn't work let me know
> > 
> > 
> > Can you tell me how to get the api-for-own-servers working? Ive got the main script working, but dont know how the api-for-own-servers works.. Do i need it to call it like : https://localhosti/api-for-own-servers/?url=https://www.xvideos.com/video59934029/
> 
> yes, what [api-for-own-servers](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/tree/main/api-for-own-servers) does is to act as a proxy to make requests from it and not the main script, so you avoid burning the ip of the main server (the main script)
> 
> to use it, you must place it in the root or in any part of your server, then add it to the list of servers in [sources.json](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/blob/main/src/servers/sources.json) following the format shown there
> 
> I will take as an example the website https://appsdev.cyou/xv-ph-rt/
> 
> the main script is at https://appsdev.cyou/xv-ph-rt/ and the [api-for-own-servers](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/tree/main/api-for-own-servers) script is in https://tmp01.appsdev.cyou/
> 
> so in [sources.json](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/blob/main/src/servers/sources.json#L37) it would look like this
> 
> ```json
> {
>     "id": "xvideos",
>     "url": "https://tmp01.appsdev.cyou/?url={url}",
>     "category": ["primary"],
>     "media": {
>         "hls": {
>             "all": "VideoHLS\\('(.*?)'\\)"
>         },
>         "mp4": {
>             "high": "High\\('(.*?)'\\)",
>             "low": "Low\\('(.*?)'\\)"
>         }
>     },
>     "data": {
>         "thumb": "ThumbUrl169\\('(.*?)'\\)",
>         "duration": "duration\" content=\"(.*?)\""
>     }
> },
> ```
> 
> if the script is not in the root, indicate its location Ex. `https://tmp01.appsdev.cyou/api-for-own-servers/?url={url}`
> 
> since we use our own server, you can set as many options as you want to get
> 
> and to test that you get content use: https://tmp01.appsdev.cyou/?url=https://www.xvideos.com/video59934029/_&cookie_id=xvideos changing the domain to yours
> 
> if you want to use pornhub you must use [api-for-own-servers](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/tree/main/api-for-own-servers) either on the same server or on another one
> 
> if you have more questions let me know

Thanks for your detailed answer, its now clear.. But when I want to try fetch content from Pornhub or xvideos with the link you gave me ```https://{domain}.com/test/video/api-for-own-servers/?url=https://www.pornhub.com/view_video.php?viewkey=ph6116a13a48187/_&cookie_id=pornhub```  I get a 500 error response code. What am I doing wrong, ive checked if the http2 request is enabled on my server, and it is... You got any idea what I am doing wrong?

**Comment by Joel2B** [comment]
> Thanks for your detailed answer, its now clear.. But when I want to try fetch content from Pornhub or xvideos with the link you gave me `https://{domain}.com/test/video/api-for-own-servers/?url=https://www.pornhub.com/view_video.php?viewkey=ph6116a13a48187/_&cookie_id=pornhub` I get a 500 error response code. What am I doing wrong, ive checked if the http2 request is enabled on my server, and it is... You got any idea what I am doing wrong?

testing with the public api not to give any errors
https://tmp01.appsdev.cyou/?url=https://www.pornhub.com/view_video.php?viewkey=ph6116a13a48187/_&cookie_id=pornhub

but for pornhub, it is not necessary to include "/_", so it works.
https://tmp01.appsdev.cyou/?url=https://www.pornhub.com/view_video.php?viewkey=ph6116a13a48187&cookie_id=pornhub

check if you have an old version of the script, just yesterday I did some commits in which I updated several things

if it still doesn't work, there should be some error_log, you can show it for debugging

**Comment by Superion03** [comment]
> if it still doesn't work, there should be some error_log, you can show it for debugging

Got it working on another server with a recent Ubuntu kernel and newer PHP version.. Thanks!

**Comment by Joel2B** [comment]
> 

great, any error, problem, improvement, suggestion, comment it.
