### ISSUE TITLE
Pornhub mp4 links not reachable(Unauthorized)

### ISSUE THREAD

**Issue by Superion03** [Joel2B/XVideos-PornHub-RedTube-API#3]
Hi there,

The return values of Pornhub are not reachable, whenever i try to open one of the mp4 urls that i get back, I see:"Unauthorized
We're sorry, the request requires user authentication".

If I compare your output of the mp4 URL with mine I see the following

- `validfrom=` and `validto=` parameters are diffrent from yours and mine
- In my mp4 url the `ip=` parameter is included
- And the `hash=` parameter is diffrent fro yours and mine

Here an example of the API output from your server:
`https://ev.phncdn.com/videos/202108/13/392894661/1080P_8000K_392894661.mp4?validfrom=1643180690&validto=1643187890&rate=500k&burst=1400k&ipa={YOUR_SERVER_IP}&hash=77z0E0YMwyem74WXDaaZp8kgWAE%3D`

and this is my output i get from the api running on my server
`https://ev.phncdn.com/videos/202108/13/392894661/1080P_8000K_392894661.mp4?validfrom=1643181735&validto=1643188935&rate=500k&burst=1400k&ip={MY_SERVER_IP}&ipa={MY_SERVER_IP}&hash=nGiYZPZzM0N2MiFZjqbd2AoAiEY%3D` 

Any idea whats going wrong, has my server IP been blocked for the Pornhub CDN network? Or is there something else wrong? Btw, xvideos is working very good!

Kind regards,

**Comment by Superion03** [comment]
Btw, have there been changes in Pornhub, that you already have fixed on your side in 'extra_methods.php' ?

Because on your side it is working

**Comment by Joel2B** [comment]
hello

i see that both outputs are valid (ignoring that repeated "ip={MY_SERVER_IP}"), and the script caches the link for 1 hour, 
but you can up to 2 hours (validto - validfrom), so it wouldn't be this

you can try this:
* try it from a different server to see if it is a script problem
* if you have a browser on the server, check if you can play a video

i still think it is very unlikely that it is an IP blocking, since I have not seen any cases,
and if so you can use the [api-for-own-servers](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/tree/main/api-for-own-servers) script on another server

finally, maybe pornhub will enable access only to the one who generated the link, but at the moment they don't do it

if it still doesn't work let me know

**Comment by eyesangel** [comment]
hello there, i got the same problem here,
but it's work normal yestoday,i don't change any thing

**Comment by Joel2B** [comment]
> hello there, i got the same problem here,
> but it's work normal yestoday,i don't change any thing

hello

still not working?

maybe help you 
#2

**Comment by eyesangel** [comment]
> > hello there, i got the same problem here,
> > but it's work normal yestoday,i don't change any thing
> 
> hello
> 
> still not working?
> 
> maybe help you #2

yes
i tried http://domain/debug.php?site_id=pornhub
if i use my own server in sources.json,i got **Unauthorized** error
but use default sources.json,it's work!!
 i get no error information in my php logs

**Comment by Joel2B** [comment]
using your own server, it generates new links but you always get "Unauthorized" ?

**Comment by eyesangel** [comment]
> using your own server, it generates new links but you always get "Unauthorized" ?

eh..
yes,but it's work now
i don't know why. no reboot,no modify files, ...

**Comment by Joel2B** [comment]
oh well, if it stops working, open another issue :)
