### ISSUE TITLE
Own server Installation guide, please update

### ISSUE THREAD

**Issue by lachitmonstar** [Joel2B/XVideos-PornHub-RedTube-API#8]
Sir, I am trying to install [api-for-own-servers](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/blob/main/api-for-own-servers) on my server, and I failed. Please provide installation precess. 

Thank you.

**Comment by Joel2B** [comment]
of course

1. place the contents of the [api-for-own-servers](https://github.com/Joel2B/XVideos-PornHub-RedTube-API/blob/main/api-for-own-servers) folder somewhere on your web server,
in my case, i put in the root of the subdomain: `https://tmp01.appsdev.cyou/`

![image](https://user-images.githubusercontent.com/58922368/171518556-5ad3f831-5360-4c23-83e6-dc4e04fc9180.png)

2. open `config.php` file, and change the value of `HOST` to your domain name,
for example, https://{YOUR_DOMAIN}

![image](https://user-images.githubusercontent.com/58922368/171518310-cd579152-da1c-4de1-b65b-d05955d0f1e8.png)

to check that works, enter the link
> `https://{YOUR_DOMAIN}/?url=https://www.pornhub.com/view_video.php?viewkey=ph6116a13a48187&cookie_id=pornhub`

you must set the domain name that you configured in config.php

if everything worked fine, you should see the html of the page.

if doesn't work, probably a file called `error_log` is generated
in the location of the script,
share the contents of that file here so that i can help you.

![image](https://user-images.githubusercontent.com/58922368/171518677-3ad8125f-63cb-4a09-a0ba-ee1caf79ae8f.png)

if didn't work and a error_log file was not generated,
you should probably use the `bypass-js-check` script on your server.

any questions, please tell me.

**Comment by horasjey** [comment]
![image](https://user-images.githubusercontent.com/45363813/183493455-94f3f5b5-19bc-4db3-9a6b-77df6c0bb489.png)
can help me?

**Comment by dadang223** [comment]
Warning: require_once(PEAR/Exception.php): failed to open stream: No such file or directory in /www/wwwroot/sv1.telorku.xyz/v/api/HTTP/Request2/Exception.php on line 24

Fatal error: require_once(): Failed opening required 'PEAR/Exception.php' (include_path='.:') in /www/wwwroot/sv1.telorku.xyz/v/api/HTTP/Request2/Exception.php on line 24

in my hosting sir
